# Generated by Django 4.2 on 2023-12-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='duration',
            field=models.PositiveIntegerField(choices=[(3, '3 days'), (5, '5 days'), (7, '7 days')], default='3'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('auction', 'Auction'), ('regular', 'Regular')], default='regular', max_length=10),
        ),
    ]
