# Generated by Django 4.2 on 2023-12-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='on_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Auction',
        ),
    ]
