# Generated by Django 4.2 on 2023-12-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='category_images'),
        ),
    ]
