# Generated by Django 4.2 on 2024-01-06 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0022_auction_tags_delete_auctionreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auctioneer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='auctioneer_images')),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(default='1', max_length=100)),
                ('contact', models.CharField(default='+123 456 789', max_length=100)),
                ('authentic_rating', models.CharField(default='100', max_length=50)),
                ('warrenty_period', models.CharField(default='100', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='auctioneer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctioneer', to='product.auctioneer'),
        ),
    ]
