# Generated by Django 4.2 on 2024-01-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_alter_auction_auction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verfied',
            field=models.BooleanField(default=False),
        ),
    ]
