# Generated by Django 4.2 on 2024-01-08 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_userprofile_verfied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='verfied',
            new_name='verified',
        ),
    ]
