# Generated by Django 4.2 on 2024-01-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_rename_verfied_userprofile_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='user-default.png', upload_to='profile_pics/'),
        ),
    ]
