# Generated by Django 4.2 on 2024-01-11 07:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_bid_end_time_bid_start_time_alter_bid_auction'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(default=datetime.datetime.now)),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='product.auction')),
            ],
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
