# Generated by Django 4.2 on 2024-01-11 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_alter_bidt_options_alter_auctioneer_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='on_stock',
            new_name='live',
        ),
    ]
