# Generated by Django 4.2 on 2024-01-11 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_alter_auction_image_alter_auctioneer_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='made_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
    ]
