# Generated by Django 4.2 on 2024-01-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_alter_bids_options_auction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_vendor_auctioneer',
            field=models.BooleanField(default=False),
        ),
    ]
