# Generated by Django 4.2 on 2024-02-21 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_alter_product_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Winner',
        ),
    ]
