# Generated by Django 4.2 on 2024-02-29 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_rename_product_auction_win_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_win',
            name='invoice_no',
        ),
        migrations.RemoveField(
            model_name='auction_win',
            name='order_date',
        ),
    ]
