# Generated by Django 4.2 on 2024-02-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0050_remove_auction_win_invoice_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_win',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
