# Generated by Django 4.2 on 2024-03-01 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_winner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
